spring:
  application:
    name: loco-crew-dispather

  datasource:
    url: jdbc:postgresql://localhost:5432/dispatcher_db?currentSchema=public&user=postgres&password=postgres

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/dispatcher_db?currentSchema=public&user=postgres&password=postgres
    locations: classpath:db/migration
